name: Python-app-linter
on: [push] 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "This job running on ${{ runner.os }} ${{ job.container }} "
    - run: env
    - name: "Checkout repo"
      uses: actions/checkout@v2 
    - name: "Setup python" 
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: "Lint with pylint"
      run: |
        python lint_test.py
    - name: Build Container
      run: |
        echo "Building containre image..."
        sleep 5
    - name: Deploy to cluster
      run: |
        echo ".."
    - run: echo "This job's status is ${{ job.status }}"
